# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'annotator.ui'
#
# Created: Thu Apr  8 01:05:48 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(849, 558)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(8)
        mainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 591, 511))
        self.scrollArea.setMouseTracking(False)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 589, 509))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.image = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.image.setCursor(QtCore.Qt.CrossCursor)
        self.image.setMouseTracking(True)
        self.image.setObjectName("image")
        self.horizontalLayout_4.addWidget(self.image)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(mainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 849, 25))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(10)
        self.menuBar.setFont(font)
        self.menuBar.setObjectName("menuBar")
        self.fileMenu = QtGui.QMenu(self.menuBar)
        self.fileMenu.setObjectName("fileMenu")
        mainWindow.setMenuBar(self.menuBar)
        self.toolBox = QtGui.QDockWidget(mainWindow)
        self.toolBox.setEnabled(True)
        self.toolBox.setMinimumSize(QtCore.QSize(87, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.toolBox.setFont(font)
        self.toolBox.setObjectName("toolBox")
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.horizontalLayoutWidget = QtGui.QWidget(self.dockWidgetContents_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 81, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dotButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.dotButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dotButton.setCheckable(True)
        self.dotButton.setObjectName("dotButton")
        self.horizontalLayout.addWidget(self.dotButton)
        self.rectangleButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.rectangleButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.rectangleButton.setCheckable(True)
        self.rectangleButton.setObjectName("rectangleButton")
        self.horizontalLayout.addWidget(self.rectangleButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.toolBox.setWidget(self.dockWidgetContents_2)
        mainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.toolBox)
        self.optionBox = QtGui.QDockWidget(mainWindow)
        self.optionBox.setMinimumSize(QtCore.QSize(85, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.optionBox.setFont(font)
        self.optionBox.setObjectName("optionBox")
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.dotClickButton = QtGui.QPushButton(self.dockWidgetContents_3)
        self.dotClickButton.setGeometry(QtCore.QRect(0, 10, 41, 28))
        self.dotClickButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dotClickButton.setCheckable(True)
        self.dotClickButton.setChecked(True)
        self.dotClickButton.setObjectName("dotClickButton")
        self.dotDragButton = QtGui.QPushButton(self.dockWidgetContents_3)
        self.dotDragButton.setGeometry(QtCore.QRect(0, 40, 41, 28))
        self.dotDragButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dotDragButton.setCheckable(True)
        self.dotDragButton.setObjectName("dotDragButton")
        self.dotUndoButton = QtGui.QPushButton(self.dockWidgetContents_3)
        self.dotUndoButton.setGeometry(QtCore.QRect(0, 70, 41, 28))
        self.dotUndoButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dotUndoButton.setCheckable(False)
        self.dotUndoButton.setObjectName("dotUndoButton")
        self.rectClickButton = QtGui.QPushButton(self.dockWidgetContents_3)
        self.rectClickButton.setGeometry(QtCore.QRect(0, 10, 41, 28))
        self.rectClickButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.rectClickButton.setCheckable(True)
        self.rectClickButton.setChecked(True)
        self.rectClickButton.setObjectName("rectClickButton")
        self.rectDragButton = QtGui.QPushButton(self.dockWidgetContents_3)
        self.rectDragButton.setGeometry(QtCore.QRect(0, 70, 41, 28))
        self.rectDragButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.rectDragButton.setCheckable(True)
        self.rectDragButton.setObjectName("rectDragButton")
        self.optionBox.setWidget(self.dockWidgetContents_3)
        mainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.optionBox)
        self.zoomBox = QtGui.QDockWidget(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.zoomBox.setFont(font)
        self.zoomBox.setObjectName("zoomBox")
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.zoomBox.setWidget(self.dockWidgetContents_4)
        mainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.zoomBox)
        self.statusBar = QtGui.QStatusBar(mainWindow)
        self.statusBar.setObjectName("statusBar")
        mainWindow.setStatusBar(self.statusBar)
        self.navigationBox = QtGui.QDockWidget(mainWindow)
        self.navigationBox.setMinimumSize(QtCore.QSize(150, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.navigationBox.setFont(font)
        self.navigationBox.setObjectName("navigationBox")
        self.dockWidgetContents_6 = QtGui.QWidget()
        self.dockWidgetContents_6.setObjectName("dockWidgetContents_6")
        self.verticalLayoutWidget = QtGui.QWidget(self.dockWidgetContents_6)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 141, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.prevButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.prevButton.setObjectName("prevButton")
        self.horizontalLayout_2.addWidget(self.prevButton)
        self.nextButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout_2.addWidget(self.nextButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.firstButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.firstButton.setObjectName("firstButton")
        self.horizontalLayout_3.addWidget(self.firstButton)
        self.minusTenButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.minusTenButton.setObjectName("minusTenButton")
        self.horizontalLayout_3.addWidget(self.minusTenButton)
        self.plusTenButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.plusTenButton.setObjectName("plusTenButton")
        self.horizontalLayout_3.addWidget(self.plusTenButton)
        self.lastButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.lastButton.setObjectName("lastButton")
        self.horizontalLayout_3.addWidget(self.lastButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.imageComboBox = QtGui.QComboBox(self.verticalLayoutWidget)
        self.imageComboBox.setObjectName("imageComboBox")
        self.verticalLayout.addWidget(self.imageComboBox)
        self.navigationBox.setWidget(self.dockWidgetContents_6)
        mainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.navigationBox)
        self.openAction = QtGui.QAction(mainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openAction.setIcon(icon)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.openAction.setFont(font)
        self.openAction.setObjectName("openAction")
        self.exitAction = QtGui.QAction(mainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitAction.setIcon(icon1)
        self.exitAction.setObjectName("exitAction")
        self.fileMenu.addAction(self.openAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.exitAction)
        self.menuBar.addAction(self.fileMenu.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QtGui.QApplication.translate("mainWindow", "Annotator", None, QtGui.QApplication.UnicodeUTF8))
        self.fileMenu.setTitle(QtGui.QApplication.translate("mainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setWindowTitle(QtGui.QApplication.translate("mainWindow", "Toolbox", None, QtGui.QApplication.UnicodeUTF8))
        self.dotButton.setText(QtGui.QApplication.translate("mainWindow", "dot", None, QtGui.QApplication.UnicodeUTF8))
        self.rectangleButton.setText(QtGui.QApplication.translate("mainWindow", "rect", None, QtGui.QApplication.UnicodeUTF8))
        self.optionBox.setWindowTitle(QtGui.QApplication.translate("mainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.dotClickButton.setText(QtGui.QApplication.translate("mainWindow", "click", None, QtGui.QApplication.UnicodeUTF8))
        self.dotDragButton.setText(QtGui.QApplication.translate("mainWindow", "drag", None, QtGui.QApplication.UnicodeUTF8))
        self.dotUndoButton.setText(QtGui.QApplication.translate("mainWindow", "undo", None, QtGui.QApplication.UnicodeUTF8))
        self.rectClickButton.setText(QtGui.QApplication.translate("mainWindow", "click2", None, QtGui.QApplication.UnicodeUTF8))
        self.rectDragButton.setText(QtGui.QApplication.translate("mainWindow", "drag2", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomBox.setWindowTitle(QtGui.QApplication.translate("mainWindow", "Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.navigationBox.setWindowTitle(QtGui.QApplication.translate("mainWindow", "Navigation", None, QtGui.QApplication.UnicodeUTF8))
        self.prevButton.setToolTip(QtGui.QApplication.translate("mainWindow", "Previous image", None, QtGui.QApplication.UnicodeUTF8))
        self.prevButton.setText(QtGui.QApplication.translate("mainWindow", "-1", None, QtGui.QApplication.UnicodeUTF8))
        self.prevButton.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.nextButton.setToolTip(QtGui.QApplication.translate("mainWindow", "Next image", None, QtGui.QApplication.UnicodeUTF8))
        self.nextButton.setText(QtGui.QApplication.translate("mainWindow", "+1", None, QtGui.QApplication.UnicodeUTF8))
        self.nextButton.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.firstButton.setToolTip(QtGui.QApplication.translate("mainWindow", "First image", None, QtGui.QApplication.UnicodeUTF8))
        self.firstButton.setText(QtGui.QApplication.translate("mainWindow", "|<", None, QtGui.QApplication.UnicodeUTF8))
        self.minusTenButton.setToolTip(QtGui.QApplication.translate("mainWindow", "10 images back", None, QtGui.QApplication.UnicodeUTF8))
        self.minusTenButton.setText(QtGui.QApplication.translate("mainWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.plusTenButton.setToolTip(QtGui.QApplication.translate("mainWindow", "10 images forward", None, QtGui.QApplication.UnicodeUTF8))
        self.plusTenButton.setText(QtGui.QApplication.translate("mainWindow", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.lastButton.setToolTip(QtGui.QApplication.translate("mainWindow", "Last image", None, QtGui.QApplication.UnicodeUTF8))
        self.lastButton.setText(QtGui.QApplication.translate("mainWindow", ">|", None, QtGui.QApplication.UnicodeUTF8))
        self.openAction.setText(QtGui.QApplication.translate("mainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.openAction.setStatusTip(QtGui.QApplication.translate("mainWindow", "Open a directory containing images", None, QtGui.QApplication.UnicodeUTF8))
        self.openAction.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.exitAction.setText(QtGui.QApplication.translate("mainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.exitAction.setStatusTip(QtGui.QApplication.translate("mainWindow", "Exit application", None, QtGui.QApplication.UnicodeUTF8))
        self.exitAction.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))

